services:
  web:
    build: './web/'
    tty: true
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - type: bind
        source: ./web
        target: /web
      # exclude node_modules mount overwrite
      - /web/node_modules/
  pytorch-minimal-notebook:
    build: './model/'
    #
    # NB: root to open device: /dev/video0
    # see docker_run.sh for container video
    #
    user: root
    environment:
      - GRANT_SUDO="yes"
      - DISPLAY="$DISPLAY"
    ports:
      - "8888:8888"
    devices:
      - "/dev/video0:/dev/video0"
    #
    # directories accessible within jupyter env
    #
    volumes:
      - type: bind
        source: ./model
        target: /home/jovyan/model
      - type: bind
        source: ./train
        target: /home/jovyan/train
      - type: bind
        source: ./scratch
        target: /home/jovyan/scratch

      # run gui output to xserver
      # requires "xhost +local:docker" prior to run
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
